server:
  port: 10100 # 服务端口号
  
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/,http://localhost:9002/eureka/
            
spring:  
    application:
        name: order-service # 注册到注册中心的服务名称
    datasource:  
        name: order
        type: org.apache.tomcat.jdbc.pool.DataSource 
        driver-class-name: com.mysql.cj.jdbc.Driver  
        url: jdbc:mysql://localhost:3306/demo_db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root  
        password: dev
        defaultAutoCommit: true
        defaultTransactionIsolation: 2
        initialSize: 1  
        minIdle: 1
        maxIdle: 2
        maxActive: 2
        maxWait: 2000
        timeBetweenEvictionRunsMillis: 60000  
        minEvictableIdleTimeMillis: 300000
        testOnBorrow: true
        validationQuery: /* ping */ select 1
        validationInterval: 30000
        testWhileIdle: true