server:
  port: 13000 # 演示用客户端Web端口号

spring:
    application:
        name: demo-order-client # 演示用客户端应用名称（注册到注册中心的名称）

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:11000/eureka/ # 注册中心地址

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000