server:
  port: 12000 # 演示用客户端Web端口号

spring:
    application:
        name: client-app # 演示用客户端应用名称（注册到注册中心的名称）

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9000/eureka/ # 注册中心地址

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000

# 打开FeignClient的Debug日志
logging.level.org.liuzhibin.research.feign.OrderServiceViaZuulFeignClient: DEBUG
logging.level.org.liuzhibin.research.feign.OrderServiceNoZuulFeignClient: DEBUG
logging.level.org.liuzhibin.research.feign.DemoServiceViaZuulFeignClient: DEBUG
logging.level.org.liuzhibin.research.feign.DemoServiceNoZuulFeignClient: DEBUG